BICEPS: Biceps Class Reference
Biceps Class Reference
The Biceps-Code calls the different libraries, also parses the commandline for parameters.
Public Member Functions
Biceps (int argc, char *argv[])
Private Member Functions
void checkTupleConversion () const
string convertTupleString (const string &sequence) const
double findCutoff (std::vector< double > &mu, std::vector< double > &sigma, int selector=2)
void initialize (int argc, char *argv[])
bool isDosFile (std::string &filename)
void loadAAModifications ()
void readMGF ()
double returnConfidence (double score, double mu, double sigma) const
bool run_programs ()
PepspliceResult runPepsplice (bool mutation, int pepN1, int pepN2, int dirN1, int dirN2)
void showLicenses ()
void writeCompleteResult (const std::vector< PepspliceResult > &pepResults, const std::vector< int > &indices, const std::vector< string > &titles, const std::vector< int > &labels, const std::vector< double > &mu, const std::vector< double > &sigma, const double cutoff) const
void writeFasta (std::vector< PepspliceResult > &pepResults)
int writeResult (std::ostream &os, const Pepsplice::PepspliceResult &res, const int specIndex, const std::string &title) const
Private Attributes
map< unsigned char, char > aamod
vector< string > directOp
Fasta fasta
general_options genOp
unsigned int mgfId
vector< string > pepnOp
vector< PepspliceResult > pepResults
vector< string > pepsOp
Detailed Description
The Biceps-Code calls the different libraries, also parses the commandline for parameters.
Author:
Buote Xu (Buote.Xu@stud.uni-heidelberg.de)
Date:
January, 2010 This class represents the glue to unite the different libraries. It works in several steps: At the beginning, initialize(argc, argv) will call the CommandParser, which is responsible for parsing the command-line parameters and changing the settings/flags accordingly. During the next step, the mandatory fasta-database will be indexed and be made ready for later parsing. The other mandatory parameter corresponds to the MGF-file, which is parsed line by line via readMGF . Every time a complete spectrum is parsed (with BEGIN IONS and END IONS lines), it gBiceps passed in a temporary file to Directag/Pepnovo in run_programs. One of these two libraries (or even both, depending on the settings), creates a list of viable tags corresponding to the current spectrum found in the mgf. runPepsplice calls the Fasta class to process these tags and matching them to the original fasta, to create a customized fasta to pass to the pepsplice-library along with the mgf. This will happen several times per spectrum, as different parameters to pepsplice have to be processed if the result wasn't good enough yet. When all of it is finished, the best pepsplice-outputs for every spectrum is saved and written to a file at the end, while cutting out some of them according to a quantile calculated by findCutoff
Example Usage:
 int main(int argc, char *argv[])
 {
   Biceps(argc,argv);
 }
Definition at line 64 of file biceps.h.
Constructor & Destructor Documentation
Biceps (int argc, char * argv[])
Standard constructor, call it with argc and argv.
Definition at line 162 of file biceps.h.
References initialize().
Member Function Documentation
void checkTupleConversion () const [private]
print this->aamod;
Definition at line 695 of file biceps.cpp.
References aamod.
string convertTupleString (const string & sequence) const [private]
converts Pepsplice output to readable output, has to be done because of the internal modifications
Definition at line 625 of file biceps.cpp.
References aamod.
Referenced by writeResult().
double findCutoff (std::vector< double > & mu, std::vector< double > & sigma, int selector = 2) [private]
call gmm-bic and find the quantile, selector sBiceps the number of gaussians.
Parameters:
[out] mu saves the mu-values of the different gaussians
[out] sigma saves the sigma-values of the different gaussians
Definition at line 604 of file biceps.cpp.
Referenced by readMGF().
void initialize (int argc, char * argv[]) [private]
Call the CommandParser to get all the needed parameters, start the Fasta parsing and go through the .mgf afterwards.
Definition at line 6 of file biceps.cpp.
References general_options::debug, Fasta::debuglevel, directOp, fasta, general_options::fastaname, genOp, loadAAModifications(), Fasta::loadBigFasta(), mgfId, pepnOp, pepsOp, readMGF(), and showLicenses().
Referenced by Biceps().
bool isDosFile (std::string & filename) [private]
check for line endings, 1 if '
', 0 otherwise
Definition at line 59 of file biceps.cpp.
Referenced by readMGF().
void loadAAModifications () [private]
parse the inAAModifications.param file which is also necessary for pepsplice, save internal modifications in AA weights in this->aamod;
Definition at line 640 of file biceps.cpp.
References aamod.
Referenced by initialize().
void readMGF () [private]
parse the MGF file, this function will always parse inbetween BEGIN IONS and END IONS and write this to a temporary file which will be parsed by the other programs.
Definition at line 97 of file biceps.cpp.
References fasta, findCutoff(), genOp, Fasta::initializeMGF(), isDosFile(), mgfId, general_options::mgfname, general_options::numTags, pepResults, run_programs(), Fasta::setNumTags(), general_options::sSpectrumFN, writeCompleteResult(), writeFasta(), and writeResult().
Referenced by initialize().
double returnConfidence (double score, double mu, double sigma) const [private]
give a confidence for the result-quality
Definition at line 688 of file biceps.cpp.
bool run_programs () [private]
run pepnovo/directag and pepsplice, return 1 if it was successful and a legit Sequence was found, 0 otherwise.
Definition at line 403 of file biceps.cpp.
References Fasta::clearTags(), general_options::debug, Fasta::directags, directOp, fasta, genOp, Fasta::getNumTags(), Fasta::loadTags(), general_options::mgfname, general_options::mutation, general_options::numTags, pepnOp, Fasta::pepntags, Fasta::printTags(), runPepsplice(), and general_options::tool.
Referenced by readMGF().
PepspliceResult runPepsplice (bool mutation, int pepN1, int pepN2, int dirN1, int dirN2) [private]
pep and dir N1/N2 are the lower / upper limits for the tagindices which should be considered, tags are saved in the fasta class and created by Directag/Pepnovo
Parameters:
[in] mutation bool, use mutated tags or not
[in] pepN1 lower bound for the tagindices for pepnovo
[in] pepN2 upper bound for the tagindices for pepnovo
[in] dirN1 lower bound for the tagindices for directag
[in] dirN2 upper bound for the tagindices for directag
Definition at line 527 of file biceps.cpp.
References Fasta::createFasta(), Fasta::directags, fasta, genOp, Fasta::getMatches(), general_options::max_penalties, general_options::max_penalties_mutated, Fasta::pepntags, pepsOp, and general_options::tool.
Referenced by run_programs().
void showLicenses () [private]
show Pepnovo/Directag/Pepsplice Licenses
Definition at line 32 of file biceps.cpp.
References genOp, and general_options::tool.
Referenced by initialize().
void writeCompleteResult (const std::vector< PepspliceResult > & pepResults, const std::vector< int > & indices, const std::vector< string > & titles, const std::vector< int > & labels, const std::vector< double > & mu, const std::vector< double > & sigma, const double cutoff) const [private]
similar to writeResult, also add confidence to the result and mgf-index
Parameters:
[in] pepResults a vector with pepsplice-results from different spectra
[in] indices a vector with the indices of the spectra, fitting to pepResults
[in] titles the info-tags of the spectra
[in] labels vector with the labels of the results according to gmm-bic
Definition at line 327 of file biceps.cpp.
Referenced by readMGF().
void writeFasta (std::vector< PepspliceResult > & pepResults) [private]
write the final fasta with modifications.
Definition at line 353 of file biceps.cpp.
References Fasta::bigfasta, Fasta::bigfasta_descriptions, fasta, genOp, and general_options::mgfname.
Referenced by readMGF().
int writeResult (std::ostream & os, const Pepsplice::PepspliceResult & res, const int specIndex, const std::string & title) const [private]
create a title-textfile and write all results with penalty, bic etc
Parameters:
[out] os stream to log to, default value: file
[in] res a pepspliceresult from runPrograms
[in] specIndex index of the current spectrum in the mgf
[in] title info for the current spectrum
Definition at line 587 of file biceps.cpp.
References convertTupleString().
Referenced by readMGF().
Member Data Documentation
map<unsigned char, char> aamod [private]
Pepsplice uses a separate in_AAmodifications.param to decide the possible mutations. This map is needed to re-translate the modifications into ascii for logging reasons.
Definition at line 89 of file biceps.h.
Referenced by checkTupleConversion(), convertTupleString(), and loadAAModifications().
vector<string> directOp [private]
Options for directag, for number of tags, mgf-name etc.
Definition at line 67 of file biceps.h.
Referenced by initialize(), and run_programs().
Fasta fasta [private]
See class Fasta documentation.
Definition at line 82 of file biceps.h.
Referenced by initialize(), readMGF(), run_programs(), runPepsplice(), and writeFasta().
general_options genOp [private]
general_options, for Number of tags etc.
Definition at line 76 of file biceps.h.
Referenced by initialize(), readMGF(), run_programs(), runPepsplice(), showLicenses(), and writeFasta().
unsigned int mgfId [private]
index of the current sub-mgf
Definition at line 85 of file biceps.h.
Referenced by initialize(), and readMGF().
vector<string> pepnOp [private]
Options for pepsplice, has fastaname, mgf-name etc.
Definition at line 70 of file biceps.h.
Referenced by initialize(), and run_programs().
vector<PepspliceResult> pepResults [private]
Save all the results of the Pepsplice outputs.
Definition at line 79 of file biceps.h.
Referenced by readMGF().
vector<string> pepsOp [private]
Options for pepnovo, holding mgf-filename etc.
Definition at line 73 of file biceps.h.
Referenced by initialize(), and runPepsplice().
The documentation for this class was generated from the following files:
biceps.h
biceps.cpp