BICEPS: Fasta Class Reference
Fasta Class Reference
Public Member Functions
Fasta ()
void clearTags ()
void createFasta (const bool mutated, const unsigned int tagsbegin, const unsigned int tagsend, const vector< Tag > &tags, std::vector< std::tuple< unsigned int, std::string, std::string > > &currentFasta)
unsigned int getMatches ()
unsigned int getNumTags ()
void initializeMGF (unsigned int charge_, float precursorMass_)
void loadBigFasta (const std::string &filename)
int loadTags (const std::string &tagstring, const vector< float > &lowPeakMzs, vector< Tag > &tags)
void matchSequences (PepspliceResult &pepresult, const std::vector< std::tuple< unsigned int, std::string, std::string > > &currentFasta)
string offerDescription (unsigned int seqid) const
void printTags ()
void setNumTags (unsigned int numTags_)
Public Attributes
int debuglevel
std::ofstream outfile
Private Member Functions
float calcWeight (const string &tag) const
unsigned int convAAToIndex (const char AA) const
double convAAToMass (const char AA) const
unsigned int cTI2 (const string &tag, const bool begin) const
std::string cutSequence (const Tag &tag, const unsigned int sequence_id, const unsigned int posTag, const int mutated, std::vector< std::tuple< unsigned int, std::string, std::string > > &currentFasta)
void expandTag (string tag, const size_t pos1, const vector< float > &lowPeakMzs, const size_t pos2, vector< Tag > &tags)
void findMutatedTags2 (const unsigned int tagsbegin, const unsigned int tagsend, const vector< Tag > &tags, std::vector< std::tuple< unsigned int, std::string, std::string > > &currentFasta)
void findTags2 (const unsigned int tagsbegin, const unsigned int tagsend, const vector< Tag > &tags, std::vector< std::tuple< unsigned int, std::string, std::string > > &currentFasta)
void indexFasta ()
void push_Tag (const string &tag, const vector< float > &lowPeakMzs, int index, vector< Tag > &tags)
Private Attributes
float aveAAweight
vector< string > bigfasta
vector< string > bigfasta_descriptions
unsigned int charge
string currentprotein
vector< Tag > directags
vector< vector< vector
< unsigned int > > > doubleIndices
unsigned int matches
unsigned int numTags
vector< Tag > pepntags
float precursorMassCharged
unsigned int tagLength
Friends
class Biceps
Detailed Description
This class encapsulates all functions to deal with a fasta database.
Fasta class This is a class for dealing with fasta-databases, like ipi.BOVIN.fasta. Searching: Given Tags, which should be of the Tag class (with length of 5), this class is able to search for matching subsequences in the database. While it is possible to only aim for identical sequences, mutations can also be considered. To provide this functionality, the complete Database has to be preloaded by the loadBigFasta(cstring) method, which will also parse and hash it. This enables us to search for the beginnings of the tags in the created hash-table, which should speed up the search as most of the sequences can be ignored. Considering mutated tags, valid hits consist of subsequences in the database which differ from the provided tags by less than 2 AAs. As actually creating all different mutations and searching for them in the database is very time-consuming, an approach is chosen where it's possible that 1 compare between the tag and the subsequence may fail, though this is only possible if we use a hash table to actually match either the beginning or the ending of a tag to the subsequence first.
Creating: Pepsplice, another library which is used in the BICEPS program, needs fasta-databases to find AA-sequences. As generic databases are too big to provide results in a reasonable time, a smaller customized one is more viable and will thus be created by the createFasta-method. The result, a std::vector<std::tuple<unsigned int, std::string, std::string> > containing modified and unmodified subsequences can then be processed by pepsplice.
Return values:
Output will be a fasta std::vector<std::tuple<unsigned int, std::string, std::string> > in the <mutated tagstring, original tagstring> format.
Example Usage:
 vector<Tag> tagbuffer;
 std::vector<std::tuple<unsigned int, std::string, std::string> > pepnFasta;
 Fasta fasta;
 fasta.loadBigFasta("ipi.CHICK.fasta");
 fasta.loadTags(string("AAAAA"), lowPeakMzs, tagbuffer);
 fasta.createFasta(1,0,0, tagbuffer, pepnFasta);
Definition at line 88 of file fasta.h.
Constructor & Destructor Documentation
Fasta ()
The Default Constructor just initializes numOfTags to 20 and averageAAWeight to 111.0, which is used for heuristic expanding of the tag.
Definition at line 23 of file fasta.cpp.
Member Function Documentation
float calcWeight (const string & tag) const [private]
calculate the sum of the AA-weights in the tag
Definition at line 162 of file fasta.cpp.
References convAAToMass().
Referenced by push_Tag().
void clearTags ()
clear all tags
Definition at line 145 of file fasta.h.
Referenced by Biceps::run_programs().
unsigned int convAAToIndex (const char AA) const [private]
switch-case for getting index of specific AA for indexFasta, should be fastest solution with jump-table
Definition at line 57 of file fasta.cpp.
Referenced by cTI2(), and indexFasta().
double convAAToMass (const char AA) const [private]
switch-case for getting the mass of a specific AA, should be fastest solution with jump-table
Definition at line 27 of file fasta.cpp.
Referenced by calcWeight(), and cutSequence().
void createFasta (const bool mutated, const unsigned int tagsbegin, const unsigned int tagsend, const vector< Tag > & tags, std::vector< std::tuple< unsigned int, std::string, std::string > > & currentFasta)
createFasta will search for (partial, depending on the mutated parameter) matches of the tags compared to the previously loaded fasta. tagsbegin and tagsend limit the indices of the searched tags, results will be written into the given currentFasta.
Parameters:
[in] mutated boolean, sets if mutated tags should also be used for the matching algorithm
[in] tagsbegin sets the first tag that should be used to search
[in] tagsend use up to tagsend - 1th tag to search for matches
[in] tags the tag-vector containing the tags to search for
[out] currentFasta this will save all the matching-results
Definition at line 173 of file fasta.cpp.
References debuglevel, findMutatedTags2(), findTags2(), matches, and outfile.
Referenced by Biceps::runPepsplice().
unsigned int cTI2 (const string & tag, const bool begin) const [private]
calculating the index of a Tag, if begin ==1 it uses the first two AAs, otherwise it's the last two, helper function to search faster for tags.
Returns the hash value of the string, using trivial hash with 19 * tag[0] + tag[1] here Probably has to be enhanced when looking at tagsize > 5 Very hardcoded, but fast!
Parameters:
[in] tag the string-portion of the tag.
[in] begin if true, get the hash for the pair of tag[0], tag[1], if false return the hash of tag[3] tag[4]
Return values:
hash-value of a pair of chars
Definition at line 153 of file fasta.cpp.
References convAAToIndex().
Referenced by findMutatedTags2(), and findTags2().
string cutSequence (const Tag & tag, const unsigned int sequence_id, const unsigned int posTag, const int mutated, std::vector< std::tuple< unsigned int, std::string, std::string > > & currentFasta) [private]
As we don't want to put whole sequences into the new fasta-database, only short sequences containing the Tag will be added to currentFasta, also return the mutated shortSequence.
Parameters:
[in] tag the tag which is matched against the fasta-entry
[in] sequence_id the number of the sequence in the fasta-database
[in] posTag the beginning of the (mutated) match between entry and tag
[in] mutated the boolean deciding whether mutations should be considered
[out] currentFasta this will save all the matching-results
Return values:
string mutated substring which matches the tag, with padding on both sides and with optional mutations
This index-list will save the occurence of the tag in the original fasta.
Definition at line 275 of file fasta.cpp.
References bigfasta, convAAToMass(), debuglevel, outfile, and tagLength.
Referenced by findMutatedTags2(), and findTags2().
void expandTag (string tag, const size_t pos1, const vector< float > & lowPeakMzs, const size_t pos2, vector< Tag > & tags) [private]
helper function, because pepnovo/directag don't differentiate between I and L, the other tags have to be generated hereby
Parameters:
[in] tag the string of the expanded tag
[in] pos1 the current letter to be expanded, will only expand if it's I or L
[in] lowPeakMzs a vector with the Peakvalues, gotten from directag or pepnovo
[out] tags the vector to write the results into
Definition at line 106 of file fasta.cpp.
References push_Tag().
Referenced by loadTags().
void findMutatedTags2 (const unsigned int tagsbegin, const unsigned int tagsend, const vector< Tag > & tags, std::vector< std::tuple< unsigned int, std::string, std::string > > & currentFasta) [private]
this function searches for partial matches (up to 1 differing AA) between given tags and the previously loaded Fasta. A speedup was possible via hashing all sequences and searching for parts of a given tag. very hardcoded, works only for size-5 tags, using the index and 'jumping' over the mutated parts.
Parameters:
[in] tagsbegin the index of the first tag to search for
[in] tagsend index+1 of the last tag to search for
[in] tags the tag-vector to search for
[out] currentFasta this will save all the matching-results
Definition at line 397 of file fasta.cpp.
References bigfasta, cTI2(), cutSequence(), doubleIndices, and matches.
Referenced by createFasta().
void findTags2 (const unsigned int tagsbegin, const unsigned int tagsend, const vector< Tag > & tags, std::vector< std::tuple< unsigned int, std::string, std::string > > & currentFasta) [private]
tagsbegin and tagsend limit the index of the used tags - we don't want to use all of them this find function will use a previously calculated index and the hashed sequences. the cut sequences will be written to currentFasta via cutSequence
Parameters:
[in] tagsbegin the index of the first tag to search for
[in] tagsend index+1 of the last tag to search for
[in] tags the tag-vector to search for
[out] currentFasta this will save all the matching-results
Definition at line 340 of file fasta.cpp.
References bigfasta, cTI2(), cutSequence(), doubleIndices, and matches.
Referenced by createFasta().
unsigned int getMatches ()
counts the number of matches btween tags and fasta
Definition at line 137 of file fasta.h.
Referenced by Biceps::runPepsplice().
unsigned int getNumTags ()
public interface
Definition at line 148 of file fasta.h.
Referenced by Biceps::run_programs().
void indexFasta () [private]
parse the complete fasta-database while indexing all occurences of all AA pairs for a quicker tag-search later
Definition at line 251 of file fasta.cpp.
References bigfasta, convAAToIndex(), and doubleIndices.
Referenced by loadBigFasta().
void initializeMGF (unsigned int charge_, float precursorMass_)
initializeMGF sets the charge and the precursormass, it's used in the main function for every additional spectrum. the precursormass will be multiplicated with the charge and stored in the Fasta class
Definition at line 131 of file fasta.h.
Referenced by Biceps::readMGF().
void loadBigFasta (const std::string & filename)
loadBigFasta needs the filename (as a std::string) of the fastafile, it will then call some private functions.
They will then create an easier to search fastafile with replaced I AAs, a hashing index containing all 2-combinations of AAs will also be made
Parameters:
[in] filename of the fasta-database to index and match/search later, e.g. loadBigFasta(string("ipi.BOVIN.fasta"))
Definition at line 194 of file fasta.cpp.
References bigfasta, bigfasta_descriptions, and indexFasta().
Referenced by Biceps::initialize().
int loadTags (const std::string & tagstring, const vector< float > & lowPeakMzs, vector< Tag > & tags)
This method takes the unmodified tagstring, changes the L AAs to I for performance reasons and fills the internal tag vectors for further processing.
Parameters:
[in] tagstring string which is made up of the different tags found by pepnovo/directag, no spaces.
[in] lowPeakMzs is also calculated by pepnovo/directag, it has to be multiplicated by the spectrum charge-1 to calculate the mass.
Return values:
int number of tags found/created + 1
Definition at line 87 of file fasta.cpp.
References expandTag(), and tagLength.
Referenced by Biceps::run_programs().
string offerDescription (unsigned int seqid) const
insert id, get the description in the fastafile for that specific id.
Parameters:
[in] seqid id of the spectrum you want the information for
Return values:
string the description of that specific spectrum taken from the fasta file
Definition at line 142 of file fasta.h.
Referenced by Biceps::writeResult().
void printTags ()
just print all of the currently saved tags in the fasta class, this will be pepnTags and direcTags
Definition at line 135 of file fasta.cpp.
References directags, and pepntags.
Referenced by Biceps::run_programs().
void push_Tag (const string & tag, const vector< float > & lowPeakMzs, int index, vector< Tag > & tags) [private]
nothing special, just a short way to add to the tags
Parameters:
[in] tag the string of the to be saved tag
[in] lowPeakMzs a vector with the Peakvalues, gotten from directag or pepnovo
[in] index the index of the corresponding peakvalue in lowPeakMzs
[out] tags the vector to write the results into
Definition at line 129 of file fasta.cpp.
References calcWeight().
Referenced by expandTag().
void setNumTags (unsigned int numTags_)
change the limit of saved tags, default is 20 per directag/pepnovo program.
Definition at line 134 of file fasta.h.
Referenced by Biceps::readMGF().
Member Data Documentation
vector<string> bigfasta [private]
indexed fasta file
Definition at line 245 of file fasta.h.
Referenced by cutSequence(), findMutatedTags2(), findTags2(), indexFasta(), loadBigFasta(), and Biceps::writeFasta().
vector<string> bigfasta_descriptions [private]
descriptions for later output
Definition at line 249 of file fasta.h.
Referenced by loadBigFasta(), and Biceps::writeFasta().
int debuglevel
change the debug level, 1 is default. Higher debuglevels will provide file-logging.
Definition at line 239 of file fasta.h.
Referenced by createFasta(), cutSequence(), and Biceps::initialize().
vector<Tag> directags [private]
the tags from directag, which are produced by loadTags()
Definition at line 251 of file fasta.h.
Referenced by printTags(), Biceps::run_programs(), and Biceps::runPepsplice().
vector<vector<vector<unsigned int> > > doubleIndices [private]
Indexing all Tags with 2 AAs, for easier/faster search later It's a pretty ugly triple-vector, access is done via doubleIndices[SequenceID][hash_of_pair][entry];.
Definition at line 270 of file fasta.h.
Referenced by findMutatedTags2(), findTags2(), and indexFasta().
unsigned int matches [private]
number of matches
Definition at line 243 of file fasta.h.
Referenced by createFasta(), findMutatedTags2(), and findTags2().
unsigned int numTags [private]
number of tags
Definition at line 259 of file fasta.h.
std::ofstream outfile
if Debugoutput is needed, outfile will be used for saving the resulting fasta-database.
Definition at line 237 of file fasta.h.
Referenced by createFasta(), and cutSequence().
vector<Tag> pepntags [private]
the tags from pepnovo, which are produced by loadTags()
Definition at line 253 of file fasta.h.
Referenced by printTags(), Biceps::run_programs(), and Biceps::runPepsplice().
unsigned int tagLength [private]
not used at the moment, as the hardcoded tagLength is 5 for performance reasons.
Definition at line 256 of file fasta.h.
Referenced by cutSequence(), and loadTags().
The documentation for this class was generated from the following files:
fasta.h
fasta.cpp